image: node:16

definitions:
    caches:
        nodemodules: ./node_modules
        accountnodemodules: ./src/pages/account/kidsloop-pass-frontend/client/node_modules
        cypress: $HOME/.cache/Cypress
    steps:
        - step: &install-dependencies
              name: Install npm dependencies (with cache)
              caches:
                  - node
              script:
                  - npm i --no-progress --no-audit
              artifacts:
                  - node_modules/**
        - step: &install-dependencies-strict
              name: Install npm dependencies (no cache)
              caches:
                  - node
              script:
                  - npm ci --no-progress --no-audit
              artifacts:
                  - node_modules/**
        - step: &checks
              name: Check JS
              script:
                  - npm run check
        - step: &test
              name: Test
              script:
                  - npm test -- --coverage
        - step: &load-alpha-env
              name: Load alpha-dev .env file
              script:
                  - cp deploy/config/internal/.env.alpha ./.env
              artifacts:
                  download: false
                  paths:
                      - ./.env
        - step: &build
              name: Build
              script:
                  - npm run build
        - step: &cypress-tests
              name: "UI Cypress Regression Tests - Chrome Browser - $ENVIRONMENT environment - $VIEWPORT viewport"
              image: cypress/browsers:node16.5.0-chrome97-ff96
              script:
                  - npm run test:$ENVIRONMENT:$VIEWPORT
                  - npm run e2e:reports
              caches:
                  - cypress
                  - node
              artifacts:
                  # store any generates images and videos as artifacts
                  - cypress/screenshots/**
                  - cypress/cucumber-json
                  - cypress/videos/**
                  - test-reports/**
                  - test-reports/cucumber-report/cucumber-htmlreport/index.html

clone:
    lfs: true

pipelines:
    branches:
        dev:
            - step: *install-dependencies-strict
            - step: *checks
            - step: *test
            - step: *load-alpha-env
            - step: *build

    pull-requests:
        "**":
            - step: *install-dependencies
            - step: *checks
            - step: *test
            - step: *load-alpha-env
            - step: *build

    custom:
        deploy:
            - variables:
                  - name: KIDSLOOP_REGION
                  - name: KIDSLOOP_ENV
                  - name: KIDSLOOP_PASS_ENV

            - step:
                  name: "Build NPM"
                  image: node:lts
                  script:
                      - npm ci
                      - cp deploy/config/$KIDSLOOP_REGION/.env.$KIDSLOOP_ENV ./.env
                      - npm run build
                  caches:
                      - nodemodules
                  artifacts:
                      - dist/*

            - step:
                  name: "Build & Push Docker image"
                  image: python:3.9-alpine
                  script:
                      - pip3 install -U awscli
                      - mv dist deploy/

                      - export BRANCH_TAG=$(echo "$BITBUCKET_BRANCH" | sed -E 's/([^0-9a-zA-Z]+)/-/g' | awk '{print tolower($0)}')
                      - export REPO=$DOCKER_REPO_URL/kidsloop-auth-frontend # DOCKER_REPO_URL is workspace wide variable
                      - export COMMIT_TAG=$(echo $BITBUCKET_COMMIT | cut -c1-7)
                      - if test -z "$BRANCH_TAG"; then export TAG=commit-$KIDSLOOP_REGION-$KIDSLOOP_ENV; else export TAG=$BRANCH_TAG-$KIDSLOOP_REGION-$KIDSLOOP_ENV; fi

                      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin $DOCKER_REPO_URL
                      - docker build -t auth-frontend deploy/

                      - docker tag auth-frontend:latest $REPO:$TAG
                      - docker tag auth-frontend:latest $REPO:$TAG-latest
                      - docker tag auth-frontend:latest $REPO:$TAG-$BITBUCKET_BUILD_NUMBER
                      - docker tag auth-frontend:latest $REPO:$TAG-$COMMIT_TAG

                      - if test -n "$BRANCH_TAG"; then docker push $REPO:$TAG; fi
                      - if test -n "$BRANCH_TAG"; then docker push $REPO:$TAG-latest; fi
                      - docker push $REPO:$TAG-$BITBUCKET_BUILD_NUMBER
                      - docker push $REPO:$TAG-$COMMIT_TAG

                  services:
                      - docker

        cypress-tests:
            - variables:
                  - name: VIEWPORT
                    default: "default"
                  - name: ENVIRONMENT
                    default: "sso"
            - step:
                  <<: *install-dependencies
                  image: cypress/browsers:node16.5.0-chrome97-ff96
            - step: *cypress-tests
