pipelines:
  custom:
    deploy:
    - variables:
          - name: KIDSLOOP_REGION
          - name: KIDSLOOP_ENV
    
    - step:
        name: 'Clone Kidsloop Pass'    
        image: node:lts
        script:
          - git submodule update --init --recursive --force
        artifacts:
         - src/pages/account/kidsloop-pass-frontend/**

    - step:
        name: 'Build NPM'
        image: node:lts
        script:
          - npm i
          - mv deploy/config/$KIDSLOOP_REGION/webpack.$KIDSLOOP_ENV.config.js ./webpack.$KIDSLOOP_ENV.config.js
          - npm run build:$KIDSLOOP_ENV
        caches:
          - nodemodules
        artifacts:
         - dist/*
         - src/pages/account/kidsloop-pass-frontend/**

    - step:
        name: 'Build Kidsloop Pass'
        image: node:lts
        script:
          - cd src/pages/account/kidsloop-pass-frontend/client
          - npm i
          - npm run build:prod-$KIDSLOOP_REGION
        caches:
          - accountnodemodules
        artifacts:
          - dist/*
          - src/pages/account/kidsloop-pass-frontend/client/dist/*

    - step:
        name: "Build & Push Docker image"
        image: python:3.9-alpine
        script:
          - pip3 install -U awscli
          - mv src/pages/account/kidsloop-pass-frontend/client/dist ./dist/account
          - mv dist deploy/

          - export BRANCH_TAG=$(echo "$BITBUCKET_BRANCH" | sed -E 's/([^0-9a-zA-Z]+)/-/g' | awk '{print tolower($0)}')
          - export TAG=$BRANCH_TAG-$KIDSLOOP_REGION-$KIDSLOOP_ENV
          - export REPO=$DOCKER_REPO_URL/kidsloop-auth-frontend   # DOCKER_REPO_URL is workspace wide variable
          - export COMMIT_TAG=$(git rev-parse --short HEAD)

          - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin $DOCKER_REPO_URL
          - docker build -t auth-frontend deploy/
          
          - docker tag auth-frontend:latest $REPO:$TAG
          - docker tag auth-frontend:latest $REPO:$TAG-latest
          - docker tag auth-frontend:latest $REPO:$TAG-$BITBUCKET_BUILD_NUMBER
          - docker tag auth-frontend:latest $REPO:$TAG-$COMMIT_TAG

          - docker push $REPO:$TAG
          - docker push $REPO:$TAG-latest
          - docker push $REPO:$TAG-$BITBUCKET_BUILD_NUMBER
          - docker push $REPO:$TAG-$COMMIT_TAG

        services:
          - docker

definitions:
  caches:
    nodemodules: ./node_modules
    accountnodemodules: ./src/pages/account/kidsloop-pass-frontend/client/node_modules