export default {
    languageCodes: new Map<string, string>([
        [`English`, `en`],
        [ `Spanish`, `es` ],
        [ `Chinese`, `zh-CN` ],
        [ `Korean`, `ko` ],
        [ `Vietnamese`, `vi` ],
        [ `Thai`, `th` ],
        [ `Indonesia`, `id` ],
    ]),
    languageSelectorText: new Map<string, string>([
        [ `Spanish`, `Español` ],
        [ `Chinese`, `汉语 (简体)` ],
        [ `Korean`, `한국어` ],
        [ `Vietnamese`, `Tiếng Việt` ],
        [ `Thai`, `ภาษาไทย` ],
        [ `Indonesia`, `bahasa Indonesia` ],
    ]),
    emailAddressOrPhoneNumberText: new Map<string, string>([
        [ `English`, `Email Address or Phone Number` ],
        [ `Spanish`, `**\n Correo electrónico\n **` ],
        [ `Chinese`, `汉语 (简体)` ],
        [ `Korean`, `한국어` ],
        [ `Vietnamese`, `Tiếng Việt` ],
        [ `Thai`, `ภาษาไทย` ],
        [ `Indonesia`, `bahasa Indonesia` ],
    ]),
    passwordText: new Map<string, string>([ 
        [ `English`, `Password` ],
        [ `Spanish`, `Contraseña` ],
        [ `Korean`, `비밀번호` ],
        [ `Chinese`, `密码` ],
        [ `Vietnamese`, `Mật khẩu` ],
        [ `Indonesia`, `Kata Sandi` ],
        [ `Thai`, `รีเซ็ตรหัสผ่าน` ],

    ]),
    forgotYourPasswordText: new Map<string, string>([ 
        [ `English`, `Forgot your password?` ],
        [ `Spanish`, `¿Olvidó su contraseña?` ],
        [ `Korean`, `암호를 잊으셨습니까?` ], 
        [ `Chinese`, `忘记了密码?` ],
        [ `Vietnamese`, `Bạn quên mật khẩu?` ],
        [ `Indonesia`, `Lupa kata sandi?` ],
        [ `Thai`, `ลืมรหัสผ่านใช่หรือไม่` ],
    ]),
    loginButtonText: new Map<string, string> ([ 
        [ `English`, `Log in` ], 
        [ `Spanish`, `Iniciar sesión` ],
        [ `Korean`, `로그인` ],[ `Chinese`, `登录` ], 
        [ `Vietnamese`, `Đăng nhập` ],
        [ `Indonesia`, `Masuk` ], 
        [ `Thai`, `เข้าสู่ระบบ` ],
    ]),
};
