export default {
    languageCodes: new Map<string, string>([
        [`English`, `en`],
        [ `Spanish`, `es` ],
        [ `Chinese`, `zh-CN` ],
        [ `Korean`, `ko` ],
        [ `Vietnamese`, `vi` ],
        [ `Thai`, `th` ],
        [ `Indonesia`, `id` ],
    ]),
    languageSelectorText: new Map<string, string>([
        [ `Spanish`, `Español` ],
        [ `Chinese`, `汉语 (简体)` ],
        [ `Korean`, `한국어` ],
        [ `Vietnamese`, `Tiếng Việt` ],
        [ `Thai`, `ภาษาไทย` ],
        [ `Indonesia`, `bahasa Indonesia` ],
    ]),
    emailAddressOrPhoneNumberText: new Map<string, string>([
        [ `English`, `Email Address or Phone Number` ],
        [ `Spanish`, `**\n Correo electrónico\n **` ],
        [ `Chinese`, `汉语 (简体)` ],
        [ `Korean`, `한국어` ],
        [ `Vietnamese`, `Tiếng Việt` ],
        [ `Thai`, `ภาษาไทย` ],
        [ `Indonesia`, `bahasa Indonesia` ],
    ]),
    passwordText: new Map<string, string>([ [ `English`, `Password` ], [ `Spanish`, `Contraseña` ] ]),
    forgotYourPasswordText: new Map<string, string>([ [ `English`, `Forgot your password?` ], [ `Spanish`, `¿Olvidó su contraseña?` ] ]),
    loginButtonText: new Map<string, string> ([ [ `English`, `Log in` ], [ `Spanish`, `Iniciar sesión` ] ]),
};
