name: Cypress integration tests

on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
        secrets:
            NODE_AUTH_TOKEN:
                required: true

jobs:
    integration-tests:
        name: Cypress integration tests
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: npm
                  registry-url: https://npm.pkg.github.com/

            - run: npm ci --no-progress --no-audit
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
                  CYPRESS_INSTALL_BINARY: 0

            - name: Cache Cypress
              id: cache-cypress
              uses: actions/cache@v2
              with:
                  path: ~/.cache/Cypress
                  key: cypress-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

            - run: npx cypress install

            - name: Cypress run
              run: npm run test:${{ inputs.environment }}

            - name: Generate reports
              run: npm run e2e:reports

            # Screenshots only generated on failures
            - uses: actions/upload-artifact@v3
              if: failure()
              with:
                  name: cypress-screenshots
                  path: cypress/screenshots

            # Test run video was always captured
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: cypress-videos
                  path: cypress/videos

            - uses: actions/upload-artifact@v3
              if: success()
              with:
                  name: cypress-reports
                  path: |
                      cypress/cucumber-json
                      test-reports/**
                      test-reports/cucumber-report/cucumber-htmlreport/index.html
