name: Cypress integration tests

on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string

jobs:
    integration-tests:
        name: Cypress integration tests
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  command: npm run test:${{ inputs.environment }}

            - name: Generate reports
              run: npm run e2e:reports

            # Screenshots only generated on failures
            - uses: actions/upload-artifact@v3
              if: failure()
              with:
                  name: cypress-screenshots
                  path: cypress/screenshots

            # Test run video was always captured
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: cypress-videos
                  path: cypress/videos

            - uses: actions/upload-artifact@v3
              if: success()
              with:
                  name: cypress-reports
                  path: |
                      cypress/cucumber-json
                      test-reports/**
                      test-reports/cucumber-report/cucumber-htmlreport/index.html
