name: Deploy to AWS

on:
    workflow_call:
        inputs:
            region:
                required: true
                type: string
            environment:
                required: true
                type: string
            aws-region:
                required: true
                type: string
            aws-s3-bucket:
                required: true
                type: string
            aws-cloudfront-distribution-id:
                required: true
                type: string
        secrets:
            aws-access-key-id:
                required: true
            aws-secret-access-key:
                required: true

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Download build
              uses: actions/download-artifact@v3
              with:
                  name: build-${{ inputs.region }}-${{ inputs.environment }}

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.aws-access-key-id }}
                  aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
                  aws-region: ${{ inputs.aws-region }}

            - name: Upload to S3
              run: aws s3 sync dist s3://${{ inputs.aws-s3-bucket }}/latest

            - name: Cloudfront cache invalidation
              run: aws cloudfront create-invalidation --paths "/index.html" --distribution-id ${{ inputs.aws-cloudfront-distribution-id }}
              env:
                  AWS_PAGER: ""
