name: PR

on: [pull_request, push]

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: npm
                  registry-url: https://npm.pkg.github.com/

            - run: npm i --no-progress --no-audit
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Lint JS
              run: npm run check

            - name: Unit tests
              run: npm run test

            - name: Build
              run: |
                  deploy/config/internal/.env.alpha .env
                  npm run build
